version: "3"

services:
  app:
    build:
      context: .
      dockerfile:  ./docker/app/Dockerfile
    volumes:
      - ./:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge